### ISSUE TITLE
能否添加一个带联动效果的tittle的demo

### ISSUE THREAD

**Issue by RicardoJiang** [DylanCaiCoding/LoadingStateView#1]
能否添加一个带联动效果的tittle的demo,示例中并未给出这样的例子

**Comment by DylanCaiCoding** [comment]
> 能否添加一个带联动效果的tittle的demo,示例中并未给出这样的例子

抱歉，之前还没想好写怎么样的示例。已经更新补充了，其它的示例代码进行了优化，方便阅读。
