### ISSUE TITLE
Toolbar会被软键盘顶出屏幕，没办法固定住吗？

### ISSUE THREAD

**Issue by RyanJeson** [DylanCaiCoding/LoadingStateView#12]
布局是这样的：MainActivity是一个FrameLayout（内容） + BottomNavigationView。
HomeFrament 显示在首页上， HomeFragment是一个RecyclerView，RecyclerView里面有一个Item需要填写数据。会弹起软键盘。然后Toolbar就会被顶出屏幕

**Comment by DylanCaiCoding** [comment]
应该和本库没关系，因为只是做了代码解耦，拆开内容布局和标题栏布局，和写在一个布局是一样的效果。你试下写在一起 toolbar 应该还是会顶起来。
