### ISSUE TITLE
配合navigate使用nav().navigateUp()退回时报错（已解决）

### ISSUE THREAD

**Issue by Saul404** [DylanCaiCoding/LoadingStateView#13]
The specified child already has a parent. You must call removeView() on the child's parent first.
现在是手动removeView(it.decorView)能解决
求大佬解决一下

**Comment by DylanCaiCoding** [comment]
能具体描述下是怎么使用的吗？我也试过和 Navigation 一起使用，但没出现这个问题

**Comment by wlqjj0** [comment]
> 能具体描述下是怎么使用的吗？我也试过和 Navigation 一起使用，但没出现这个问题
<navigation xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/nav_login"
    app:startDestination="@id/loginFragment">

    <fragment
        android:id="@+id/loginFragment"
        android:name="com.ggh.module_login.ui.page.LoginFragment"
        android:label="LoginFragment"
        tools:layout="@layout/login_fragment_login" >

        <action
            android:id="@+id/login_action_loginfragment_to_registerfragment"
            app:destination="@id/registerFragment"
            app:enterAnim="@anim/frame_push_right_in"
            app:exitAnim="@anim/frame_push_right_out"
            app:popEnterAnim="@anim/frame_push_left_in"
            app:popExitAnim="@anim/frame_push_left_out"/>
    </fragment>

    <fragment
        android:id="@+id/registerFragment"
        android:name="com.ggh.module_login.ui.page.RegisterFragment"
        android:label="RegisterFragment"
        tools:layout="@layout/login_fragment_register" />
</navigation>

<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

    </data>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white">

        <androidx.fragment.app.FragmentContainerView
            android:id="@+id/nav_home_fragment"
            android:name="androidx.navigation.fragment.NavHostFragment"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:defaultNavHost="true"
            app:navGraph="@navigation/login_nav_login"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"/>

    </ScrollView>
</layout>

NavHostFragment.findNavController(this).navigate(R.id.login_action_loginfragment_to_registerfragment)进行登录到注册跳转没问题，但是 NavHostFragment.findNavController(this).navigateUp() 回退的时候会报The specified child already has a parent. You must call removeView() on the child's parent first.闪退，查看是contentView有父布局，contentParent.removeView(contentView)这样后就没问题了，麻烦您看一下，谢谢

**Comment by seeeeal** [comment]
请问是怎么解决的呢 遇到了同样的问题 ( 。 。)"
