### ISSUE TITLE
直接使用会找不到布局的viewid

### ISSUE THREAD

**Issue by crazyzjw** [DylanCaiCoding/LoadingStateView#16]
![image](https://user-images.githubusercontent.com/12543049/102981843-89fbb800-4544-11eb-8003-e26197b1a0db.png)

**Comment by crazyzjw** [comment]
basefragment实现:
![image](https://user-images.githubusercontent.com/12543049/102982138-07bfc380-4545-11eb-9ef0-50987cbb3cee.png)

**Comment by crazyzjw** [comment]
调整了下代码就可以了,认为removeview导致,其他位置还没测试
![image](https://user-images.githubusercontent.com/12543049/102987387-2f1a8e80-454d-11eb-878c-324233c107dd.png)

**Comment by DylanCaiCoding** [comment]
目前是要在请求时才调用 showLoadingView() 方法，不能一开始就调用，因为是移除和添加 View 实现的。我考虑下要不要改成显示隐藏的方式。
