### ISSUE TITLE
想再loading添加淡入淡出要怎么处理比较好

### ISSUE THREAD

**Issue by crazyzjw** [DylanCaiCoding/LoadingStateView#17]

**Comment by DylanCaiCoding** [comment]
最近比较忙，我元旦的时候再增加个配置切换动画的方法。

**Comment by DylanCaiCoding** [comment]
发布了 2.2.0-alpha 版本，调用 show 方法可以传参配置动画，具体的可以参考示例代码。实现动画类需要注意一下动画结束时的状态，不然会有问题。我后面再思考下能不能再优化一下。

https://github.com/DylanCaiCoding/LoadingHelper/blob/master/app/src/main/java/com/dylanc/loadinghelper/sample/ui/ActErrorActivity.java

https://github.com/DylanCaiCoding/LoadingHelper/blob/master/app/src/main/java/com/dylanc/loadinghelper/sample/animation/FadeAnimation.java

**Comment by crazyzjw** [comment]
> 发布了 2.2.0-alpha 版本，调用 show 方法可以传参配置动画，具体的可以参考示例代码。实现动画类需要注意一下动画结束时的状态，不然会有问题。我后面再思考下能不能再优化一下。
> 
> https://github.com/DylanCaiCoding/LoadingHelper/blob/master/app/src/main/java/com/dylanc/loadinghelper/sample/ui/ActErrorActivity.java
> 
> https://github.com/DylanCaiCoding/LoadingHelper/blob/master/app/src/main/java/com/dylanc/loadinghelper/sample/animation/FadeAnimation.java

具体会有什么问题,这两天用你的动画,貌似刚更新了又?都觉得可以

**Comment by DylanCaiCoding** [comment]
> 具体会有什么问题,这两天用你的动画,貌似刚更新了又?都觉得可以

比如隐藏动画把透明度降为 0，后面不用动画直接显示会显示一个透明度为 0 的布局什么也看不到，自己实现动画接口时需要注意一下。
