### ISSUE TITLE
请教下，TitleAdapter如何改变标题

### ISSUE THREAD

**Issue by lj250853458** [DylanCaiCoding/LoadingStateView#18]
RT，需要在tablayout切换的时候变化title

**Comment by DylanCaiCoding** [comment]
就像用 RecyclerView 适配器一样，修改数据后调用 notifyDataSetChanged() 方法。也可以在创建 viewHolder 时保存 tabLayout 对象，然后暴露一个设置 tabLayout 标题的方法来调用。
