### ISSUE TITLE
项目中使用ViewBinding,Fragment的基类中onCreateView中返回的是mBinding.getRoot()，用LoadingHelper的话Fragment的onCreateView返回的是loadingHelper.getDecorView()，请问此问题怎么解决？

### ISSUE THREAD

**Issue by zhongle588** [DylanCaiCoding/LoadingStateView#19]

**Comment by DylanCaiCoding** [comment]
先获取 binding，再用 binding.getRoot() 去创建 LoadingHelper，代码如下：

```java
binding = FragmentHomeBinding.inflate(inflater, container, false);
loadingHelper = new LoadingHelper(binding.getRoot());
return loadingHelper.getDecorView();
```

另外，建议结合我个人另一个库 [ViewBindingKTX](https://github.com/DylanCaiCoding/ViewBindingKTX) 一起封装到基类，详细的可以查看 Java 用法的 [WIKI](https://github.com/DylanCaiCoding/ViewBindingKTX/wiki/%E6%94%B9%E9%80%A0%E5%9F%BA%E7%B1%BB-(Java)) 文档
