### ISSUE TITLE
能多加一些demo？

### ISSUE THREAD

**Issue by AndMy** [DylanCaiCoding/LoadingStateView#2]
比如自定义左边，中间，右边

**Comment by DylanCaiCoding** [comment]
> 例如自定义左边，中间，右边
这是怎么样的使用场景？

**Comment by DylanCaiCoding** [comment]
> 比如自定义左边，中间，右边

这是怎么样的使用场景？

**Comment by AndMy** [comment]
> 
> 
> > 比如自定义左边，中间，右边
> 
> 这是怎么样的使用场景？

左边：图片+图片描述 --->点击后图片作相应的动画翻转
中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
右边：分享、收藏、等多个组合布局
左边、中间、右边都有可能是组合布局

**Comment by DylanCaiCoding** [comment]
> > > 比如自定义左边，中间，右边
> > 
> > 
> > 这是怎么样的使用场景？
> 
> 左边：图片+图片描述 --->点击后图片作相应的动画翻转
> 中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
> 右边：分享、收藏、等多个组合布局
> 左边、中间、右边都有可能是组合布局

没图不太清楚是怎么样的，还有感觉不是本库的应用场景，你想在哪里使用？

**Comment by AndMy** [comment]
> 
> 
> > > > 比如自定义左边，中间，右边
> > > 
> > > 
> > > 这是怎么样的使用场景？
> > 
> > 
> > 左边：图片+图片描述 --->点击后图片作相应的动画翻转
> > 中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
> > 右边：分享、收藏、等多个组合布局
> > 左边、中间、右边都有可能是组合布局
> 
> 没图不太清楚是怎么样的，还有感觉不是本库的应用场景，你想在哪里使用？

![图片](https://user-images.githubusercontent.com/7222340/85390340-474c2980-b57b-11ea-931c-da75688509db.png)
可能我理解错了吗，“标题栏的工具”这句话

**Comment by DylanCaiCoding** [comment]
> > > > > 比如自定义左边，中间，右边
> > > > 
> > > > 
> > > > 这是怎么样的使用场景？
> > > 
> > > 
> > > 左边：图片+图片描述 --->点击后图片作相应的动画翻转
> > > 中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
> > > 右边：分享、收藏、等多个组合布局
> > > 左边、中间、右边都有可能是组合布局
> > 
> > 
> > 没图不太清楚是怎么样的，还有感觉不是本库的应用场景，你想在哪里使用？
> 
> ![图片](https://user-images.githubusercontent.com/7222340/85390340-474c2980-b57b-11ea-931c-da75688509db.png)
> 可能我理解错了吗，“标题栏的工具”这句话



> > > > > 比如自定义左边，中间，右边
> > > > 
> > > > 
> > > > 这是怎么样的使用场景？
> > > 
> > > 
> > > 左边：图片+图片描述 --->点击后图片作相应的动画翻转
> > > 中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
> > > 右边：分享、收藏、等多个组合布局
> > > 左边、中间、右边都有可能是组合布局
> > 
> > 
> > 没图不太清楚是怎么样的，还有感觉不是本库的应用场景，你想在哪里使用？
> 
> ![图片](https://user-images.githubusercontent.com/7222340/85390340-474c2980-b57b-11ea-931c-da75688509db.png)
> 可能我理解错了吗，“标题栏的工具”这句话

原来你说的只是个标题栏布局呀，我终于看懂了，前面一直想象不出来是什么东西。你没理解错，这是解耦标题栏的工具，这点需求肯定是支持的。你可以参考下 Demo 里 ToolbarAdapter 的用法，布局换成自己写的，图片文字和点击监听用构造函数传，在 onBindViewHolder 方法里设置图片文字和监听事件。我迟点加上这个示例。

**Comment by DylanCaiCoding** [comment]
> > > > > 比如自定义左边，中间，右边
> > > > 
> > > > 
> > > > 这是怎么样的使用场景？
> > > 
> > > 
> > > 左边：图片+图片描述 --->点击后图片作相应的动画翻转
> > > 中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
> > > 右边：分享、收藏、等多个组合布局
> > > 左边、中间、右边都有可能是组合布局
> > 
> > 
> > 没图不太清楚是怎么样的，还有感觉不是本库的应用场景，你想在哪里使用？
> 
> ![图片](https://user-images.githubusercontent.com/7222340/85390340-474c2980-b57b-11ea-931c-da75688509db.png)
> 可能我理解错了吗，“标题栏的工具”这句话

原来你说的只是个标题栏布局呀，我终于看懂了，前面一直想象不出来是什么东西。你没理解错，这是解耦标题栏的工具，这点需求肯定是支持的。你可以参考下 Demo 里 ToolbarAdapter 的用法，布局换成自己写的，图片文字和点击监听用构造函数传，在 onBindViewHolder 方法里设置图片文字和监听事件。我迟点加上这个示例。

**Comment by DylanCaiCoding** [comment]
> > > 比如自定义左边，中间，右边
> > 
> > 
> > 这是怎么样的使用场景？
> 
> 左边：图片+图片描述 --->点击后图片作相应的动画翻转
> 中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
> 右边：分享、收藏、等多个组合布局
> 左边、中间、右边都有可能是组合布局

已经加上了你所说的示例，可以下载最新的 app 和 pull 代码查看。

**Comment by AndMy** [comment]
> 
> 
> > > > 比如自定义左边，中间，右边
> > > 
> > > 
> > > 这是怎么样的使用场景？
> > 
> > 
> > 左边：图片+图片描述 --->点击后图片作相应的动画翻转
> > 中间：tab有做切换，配合viewpage使用；还有长长的搜索框等
> > 右边：分享、收藏、等多个组合布局
> > 左边、中间、右边都有可能是组合布局
> 
> 已经加上了你所说的示例，可以下载最新的 app 和 pull 代码查看。

谢谢，感谢
