### ISSUE TITLE
2.3.0版本下载下来是空的

### ISSUE THREAD

**Issue by boiyun** [DylanCaiCoding/LoadingStateView#20]
![image](https://user-images.githubusercontent.com/19587221/127846588-2f39acf5-fd69-4b15-8627-84e79a74e92b.png)

**Comment by boiyun** [comment]
@DylanCaiCoding 兄弟有空看一下呢

**Comment by DylanCaiCoding** [comment]
> @DylanCaiCoding 兄弟有空看一下呢

稍等，我看看

**Comment by DylanCaiCoding** [comment]
我在 Jitpack 看了也没什么问题，用同事电脑测了最新版能正常使用。你在本地删掉远程依赖缓存文件再重新同步试下。

![image](https://user-images.githubusercontent.com/23648286/127949606-0826523e-684a-4afc-84c8-4bed3fa5e291.png)

**Comment by boiyun** [comment]
这个提示有关系吗
![image](https://user-images.githubusercontent.com/19587221/127952395-127b7862-def2-45df-a945-aeef1da074dc.png)

**Comment by DylanCaiCoding** [comment]
> 这个提示有关系吗
> ![image](https://user-images.githubusercontent.com/19587221/127952395-127b7862-def2-45df-a945-aeef1da074dc.png)

看了下是说 Kotlin 编译器的版本不一样导致不能反编译代码，你试下能不能调用到 LoadingHelper。

**Comment by boiyun** [comment]
不行，我找同事电脑试一下看看

**Comment by DylanCaiCoding** [comment]
不知道会不会和 Kotlin 插件有关，有新版我都会更新的，我的目前是 1.5.20

```
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
```

**Comment by boiyun** [comment]
我是1.4.21，我改成1.5.20了，也不行，别的库也没事呀，我下午再看看，不行先用旧版的

**Comment by boiyun** [comment]
![image](https://user-images.githubusercontent.com/19587221/127954792-6af4ac9f-7987-4d99-908b-834329a73e1e.png)
这是缓存里面的

**Comment by boiyun** [comment]
我同事那也不行，我先用旧的吧，也不是不能用。。

**Comment by boiyun** [comment]
应该是你的gradle或者studio版本太高了，不整了，我这得兼容旧版本，不能升级studio，先不升级新版啦，麻烦了

**Comment by DylanCaiCoding** [comment]
你试一下升级 Kotlin 插件的版本

![image](https://user-images.githubusercontent.com/23648286/128652476-6e8075fb-e56e-4094-83ad-595fc338dda7.png)

**Comment by boiyun** [comment]
不能升级，我这studio因为要适配旧的gradle来开发sdk，所以暂时不能升级；
是不是你那太新了，如果方便，你可以试一下用旧版本打个包，估计就可以了
![image](https://user-images.githubusercontent.com/19587221/128804435-73b09093-3027-4dec-beb6-5081a241b296.png)

![企业微信截图_0c61ca08-ded2-4f7a-9450-3ddc97b7770d](https://user-images.githubusercontent.com/19587221/128804395-e198039a-4cb1-4b84-8e9e-48087867efad.png)

**Comment by DylanCaiCoding** [comment]
只是升级 Kotlin 插件，不是升级 Gradle 插件，应该不影响

**Comment by boiyun** [comment]
升级kotlin插件就行了，感谢，之前改了一直编译不了，后来换个热点才行。。感谢
