### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by shenbh** [DylanCaiCoding/LoadingStateView#21]
LoadingHelper-master\app\src\main\java\com\dylanc\loadinghelper\sample\base\BaseActivity.java:52: 错误: LoadingHelper.ContentAdapter 在 LoadingHelper 中是 private 访问控制
  public void setContentView(int layoutResID, @IdRes int contentViewId, LoadingHelper.ContentAdapter<?> contentAdapter) {

**Comment by DylanCaiCoding** [comment]
不好意思才看到，在 2.3.0 版本把 ContentAdapter 移除了，感觉用处不大，而且 Kotlin 委托能更好的胜任。改了工具类忘记改示例代码。你再拉一下最新的代码应该能正常跑起来了。
