### ISSUE TITLE
如果使用FragmentContainerView 在fragment添加View时回报错

### ISSUE THREAD

**Issue by yudu233** [DylanCaiCoding/LoadingStateView#22]
Views added to a FragmentContainerView must be associated with a Fragment

请问这样该如何添加

**Comment by DylanCaiCoding** [comment]
不会意思现在才看到，GitHub 的通知怪怪的，有时会不通知。请问解决了吗？没有的话发 onCreateView 的代码看一下。

**Comment by yudu233** [comment]
我差资料说明是: FragmentContainerView只允许由Fragment.onCreateView(LayoutInflater, ViewGroup, Bundle)返回的view。试图添加任何其他视图将导致IllegalStateException。

onCreateView 里也没有别的代码  就那俩行添加view的代码

**Comment by DylanCaiCoding** [comment]
需要在 onCreateView 返回 loadingHelper.decorView，代码如下：

```kotlin
override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
  val view = layoutInflater.inflate(R.layout.fragment_home, container, false)
  loadingHelper = LoadingHelper(view)
  return loadingHelper.decorView
}
```

**Comment by yudu233** [comment]
不对吧  这个时候contentView确实是fragment的布局view  创建的decorView其实和contentView是一样的 动态添加的布局在decorView之上，并不属于fragment。  此时fragment切换的时候之前添加的view还会在布局上的
