### ISSUE TITLE
LoadingStateView.addView()方法中的问题

### ISSUE THREAD

**Issue by ZhZhZhen** [DylanCaiCoding/LoadingStateView#27]
当ViewType为CONTENT，且parent为ConstrainLayout时，会对rootView.LayoutParams进行更新。
因为在调用contetnParent.addView()之前，decorView使用的LayoutParams和rootVIew为同一对象。所以这里会影响到decorView的表现。

**Comment by ZhZhZhen** [comment]
还有一个问题就是，updateView()这个方法其实是更新ViewDelegate的数据，并不能直接更新View。
我自己在使用的时候把getViewHolder()给public，直接操作ViewHolder的内容感觉更方便。

onBindViewHolder这个方法我觉得也没有使用场景，因为没有复用的情况(一个状态对应一个View)，自然用不到重新绑定

**Comment by DylanCaiCoding** [comment]
感谢反馈，抱歉现在才看到，GitHub 没通知提醒。

第一个没太看明白是什么问题，希望能再描述一下。

第二个建议很好，我会考虑一下。之前会定义 onBindViewHolder() 方法主要是希望学习成本能足够低，最开始 ViewDelegate 是叫 Adapter，用法也尽量和 Adapter 类似，还提供了 notifyDataSetChanged() 方法。不过经你这么一说感觉是没什么必要。我近期优化一下。

**Comment by ZhZhZhen** [comment]
1、DecorViewDelegate.createDecorView()这个方法会将，contentView的lp赋值给创建的decorView。
2、但是addView()这个方法在某些情况下(parent为ConstrainLayout时)会对viewHolder.rootView.lp进行更新，在ViewType为CONTENT时，该rootView即为contentView。因此此时的lp更新会影响到decorView（因为第1点是直接把contentView.lp直接赋值给decorView了）

会出现的问题具体的有点忘了。。
看代码我把他改成了创建一个lp，而不是直接使用同一个对象

**Comment by DylanCaiCoding** [comment]
已经移除了  onBindViewHolder() 和 ViewHolder，并且对用法进行了优化，现在使用起来更加简单。可以试下最新版的 [LoadingStateView.kt](https://github.com/DylanCaiCoding/LoadingStateView/blob/master/loadingstateview/src/main/java/com/dylanc/loadingstateview/LoadingStateView.kt)，用法看下新的示例代码。

不过第一个问题还是没能理解，创建新的 LayoutParams，布局位置不会受影响么，可以说下你具体怎么改的吗？

**Comment by ZhZhZhen** [comment]
我处理的不是很通用。
如果原ContentView如果在ConstaintLayout中的话，就把ContentView.lp给DecorView。ContentView自己使用一个新的MarginLayoutParams。
ps：写的时候我在想如果lp有个copy方法，或者ViewGroup.generateLayoutParams()是public的就好了。不过没找到解决办法

**Comment by ZhZhZhen** [comment]
话说，可以用LayoutParams(LayoutParams source)这个构造方法去拷贝一个lp，这样就能创建一个属性相同的lp对象

**Comment by DylanCaiCoding** [comment]
目前反馈的是 ConstraintLayout 遇到了问题，所以只拷贝了 ConstraintLayout.LayoutParams。想了下每种类型的 LayoutParams 都拷贝的话不太现实，因为有可能是用户自定义的，判断不全。

```kotlin
private fun DecorViewDelegate.createDecorView() =
  onCreateDecorView(LayoutInflater.from(contentView.context)).also { decorView ->
    contentView.layoutParams?.let {
      decorView.layoutParams = if (it is ConstraintLayout.LayoutParams) ConstraintLayout.LayoutParams(it) else it
    }
  }
```

迟点会发个 4.0 版本，会增加 Kotlin 委托的用法，在基类集成能更加简单。等我再测一测和写好新版的文档后就会发。

**Comment by DylanCaiCoding** [comment]
4.0.0 版本新用法的文档：

https://dylancaicoding.github.io/LoadingStateView/#/zh/delegate
