### ISSUE TITLE
loading 背景颜色 透明 无效

### ISSUE THREAD

**Issue by yexseven** [DylanCaiCoding/LoadingStateView#29]
loading  布局 颜色修改成透明后 无效 
在展示loading 页面是 我想看到 ContentView 里面的内容 把 loading 布局 颜色 修改 透明后 无效
在 LoadingStateView 中的 parent 控件 颜色 设置 透明也没什么用 
在 LoadingStateView 修改LinearLayout 的颜色透明也没什么用 
只能 在ActErrorActivity中 修改 window 的背景颜色 才有效果 ,但是这个时候,空布局，错误布局  都成 透明的 了 
求指教

**Comment by salmanit** [comment]
这个你得修改逻辑吧，目前的逻辑 loading，error，content同时只显示一样，其他的隐藏的。你loading设置背景无效是因为content的可见性是gone，你咋设置颜色也看不见底层内容的

**Comment by yexseven** [comment]
> 这个你得修改逻辑吧，目前的逻辑 loading，error，content同时只显示一样，其他的隐藏的。你loading设置背景无效是因为content的可见性是gone，你咋设置颜色也看不见底层内容的

懂了 谢谢
