### ISSUE TITLE
建议提供一个Java版本的LoadingHelper

### ISSUE THREAD

**Issue by huangbqsky** [DylanCaiCoding/LoadingStateView#4]
很多人没学过Kotlin，看起来很吃力，建议提供一个Java版本的LoadingHelper文件

**Comment by DylanCaiCoding** [comment]
> 很多人没学过Kotlin，看起来很吃力，建议提供一个Java版本的LoadingHelper文件

工具类是 Java 还是 Kotlin 写的都没关系，能兼容使用的。我有考虑过没学过 Kotlin 的人群，所以不管是文档和 Demo 代码都是用 Java 来写。标题栏那篇文章里不太清楚的 Kotlin 代码，可以在文档找到对应的 Java 写法，还是不懂的话看下 Demo 里具体应用的例子。
