### ISSUE TITLE
大佬，我要是只想使用 LoadingView，不用标题栏方法，怎么能让LoadingView  不遮挡标题栏呢，LoadingView可以用marginTop来控制不遮挡标题栏吗 

### ISSUE THREAD

**Issue by wang2793312458** [DylanCaiCoding/LoadingStateView#5]
loadingHelper = new LoadingHelper(this);
        loadingHelper.setOnReloadListener(this::onReload);

**Comment by wang2793312458** [comment]
我的项目里面 标题栏各种花哨不同，都写adapter的话  工程量太大

**Comment by DylanCaiCoding** [comment]
> loadingHelper = new LoadingHelper(this);
> loadingHelper.setOnReloadListener(this::onReload);

创建 LoadingHelper 对象可以传 View 的，对 View 进行 loading，建议先用 new LoadingHelper(findViewById(R.id.content_parent)) 来创建。新的项目再用适配器解耦封装。

**Comment by wang2793312458** [comment]
谢谢了，我试试
